food_control/food_control/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.contrib.auth.urls
import django.contrib.staticfiles.urls
import django.urls

import homepage.urls
import users.urls


urlpatterns = [
    django.urls.path("", django.urls.include(homepage.urls)),
    django.urls.path("admin/", django.contrib.admin.site.urls),
    django.urls.path("users/", django.urls.include(users.urls)),
    django.urls.path("users/", django.urls.include(django.contrib.auth.urls)),
]


if django.conf.settings.DEBUG:
    if django.conf.settings.MEDIA_ROOT:
        urlpatterns += django.conf.urls.static.static(
            django.conf.settings.MEDIA_URL,
            document_root=django.conf.settings.MEDIA_ROOT,
        )

    urlpatterns += django.contrib.staticfiles.urls.staticfiles_urlpatterns()

    import debug_toolbar.urls

    urlpatterns += (
        django.urls.path(
            "__debug__/",
            django.urls.include(debug_toolbar.urls),
        ),
    )

food_control/users/urls.py
from django.contrib.auth import views
import django.urls

import users.views

app_name = "users"

urlpatterns = []

# Signing up and logging in
urlpatterns += [
    django.urls.path(
        "login/",
        views.LoginView.as_view(
            template_name="users/login.html",
        ),
        name="login",
    ),
    django.urls.path(
        "logout/",
        views.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
    django.urls.path(
        "signup/",
        users.views.SignUpView.as_view(),
        name="signup",
    ),
    django.urls.path(
        "activate/<str:username>",
        users.views.ActivateView.as_view(),
        name="activate",
    ),
    django.urls.path(
        "reactivate/<int:pk>",
        users.views.ReactivateView.as_view(),
        name="reactivate",
    ),
]

# Password change and reset
urlpatterns += [
    django.urls.path(
        "password_change/",
        views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
        ),
        name="password_change",
    ),
    django.urls.path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    django.urls.path(
        "password_reset/",
        users.views.CustomPasswordResetView.as_view(),
        name="password_reset",
    ),
    django.urls.path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    django.urls.path(
        "password_reset/confirm/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=django.urls.reverse_lazy(
                "users:password_reset_complete",
            ),
        ),
        name="password_reset_confirm",
    ),
    django.urls.path(
        "password_reset/complete/",
        views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]

# User profile and list
urlpatterns += [
    django.urls.path(
        "user_list/",
        users.views.UserListView.as_view(),
        name="user_list",
    ),
    django.urls.path(
        "user_details/<int:pk>",
        users.views.UserDetailView.as_view(),
        name="user_detail",
    ),
    django.urls.path(
        "profile/",
        users.views.ProfileView.as_view(),
        name="profile",
    ),
]

food_control/templates/includes/footer.html
{% load static %}
{% load i18n %}
<footer class="py-4 bg-dark text-light">
  <div class="container text-center">
    <p class="mb-0">
      (C) <span id="year" data-time="{% now 'c' %}">{% now "Y" %}</span> {% translate "Супер-дупер крутой сайт. Все права защищены танковой броней 5-го поколения." %}
    </p>
  </div>
</footer>

<script src="{% static 'js/updateYear.js' %}"></script>

food_control/templates/includes/form.html
{% for field in form %}
<div class="mb-3">
	{% for error in field.errors %}
		<div class="alert alert-danger">
			{{ error | escape}}
		</div>
	{% endfor %}
	{{ field.label_tag }}
	{{ field }}
	{% if field.help_text %}
		<p class="help">{{ field.help_text | safe }}</p>
	{% endif %}
</div>
{% endfor %}

food_control/templates/includes/header.html
{% load static %}
{% load i18n %}
{% with request.resolver_match.view_name as view_name %}
<header class="navbar navbar-expand-lg navbar-light bg-light shadow">
  <div class="container">
    {% if view_name != 'homepage:main' %}
      <a class="navbar-brand" href="{% url 'homepage:main' %}">
        <img src="{% static 'img/logo.png' %}" height="40" alt="logo">
      </a>
    {% else %}
    <span class="navbar-brand">
      <img src="{% static 'img/logo.png' %}" height="40" alt="logo">
    </span>
    {% endif %}

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'users:profile' %}disabled{% endif %}" href="{% url 'users:profile' %}">
            {% translate "Мой профиль" %}
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'users:login' %}disabled{% endif %}" href="{% url 'users:login' %}">
            {% translate "Войти" %}
          </a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'homepage:main' %}disabled{% endif %}" href="{% url 'homepage:main' %}">
            {% translate "Главная" %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'users:user_list' %}disabled{% endif %}" href="{% url 'users:user_list' %}">
            {% translate "Пользователи" %}
          </a>
        </li>
        {% if user.is_superuser %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">
            Django-Admin
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</header>
{% endwith %}

food_control/templates/includes/no_script_silly.html
{% load i18n %}
<noscript>
    <style>
        body {
            background-color: red;
            color: white;
            text-align: center;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            font-size: 1px;
        }
        .silly-text {
            font-size: 100px;
            font-weight: bold;
        }
    </style>
    <div class="silly-text">{% translate "ВКЛЮЧИ ДЖАВА СКРИПТ" %}</div>
</noscript>

food_control/templates/includes/user_card.html
{% load static %}
{% load i18n %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<a href="{% url 'users:user_detail' user.id %}" class="text-decoration-none text-dark">
	<li class="list-group-item d-flex align-items-center">
		{% if user.profile.image %}
			<img src="{{ user.profile.get_image.url }}" alt="Профиль" class="rounded-circle me-3">
		{% else %}
			<img src="{% static 'img/racoon.jpg' %}" alt="image" class="rounded-circle me-3 racoon">
		{% endif %}
		<div>
			{% if user.first_name %}
				<h2><strong>{{ user.first_name }}</strong></h2>
			{% else %}
				<h2><strong>{% translate "Имя не указано" %}</strong></h2>
			{% endif %}
			{% if user.profile.birthday %}
				<span class="text-muted d-block">{% translate "Дата рождения" %}: {{ user.profile.birthday|date:"d.m" }}</span>
			{% else %}
				<span class="text-muted d-block">{% translate "Дата рождения" %}: {% translate "Не указано" %}</span>
			{% endif %}
		</div>
	</li>
</a>