food_control/food_control/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.contrib.auth.urls
import django.contrib.staticfiles.urls
import django.urls

import homepage.urls
import users.urls


urlpatterns = [
    django.urls.path("", django.urls.include(homepage.urls)),
    django.urls.path("admin/", django.contrib.admin.site.urls),
    django.urls.path("users/", django.urls.include(users.urls)),
    django.urls.path("users/", django.urls.include(django.contrib.auth.urls)),
]


if django.conf.settings.DEBUG:
    if django.conf.settings.MEDIA_ROOT:
        urlpatterns += django.conf.urls.static.static(
            django.conf.settings.MEDIA_URL,
            document_root=django.conf.settings.MEDIA_ROOT,
        )

    urlpatterns += django.contrib.staticfiles.urls.staticfiles_urlpatterns()

    import debug_toolbar.urls

    urlpatterns += (
        django.urls.path(
            "__debug__/",
            django.urls.include(debug_toolbar.urls),
        ),
    )

food_control/users/urls.py
from django.contrib.auth import views
import django.urls

import users.views

app_name = "users"

urlpatterns = []

# Signing up and logging in
urlpatterns += [
    django.urls.path(
        "login/",
        views.LoginView.as_view(
            template_name="users/login.html",
        ),
        name="login",
    ),
    django.urls.path(
        "logout/",
        views.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
    django.urls.path(
        "signup/",
        users.views.SignUpView.as_view(),
        name="signup",
    ),
    django.urls.path(
        "activate/<str:username>",
        users.views.ActivateView.as_view(),
        name="activate",
    ),
    django.urls.path(
        "reactivate/<int:pk>",
        users.views.ReactivateView.as_view(),
        name="reactivate",
    ),
]

# Password change and reset
urlpatterns += [
    django.urls.path(
        "password_change/",
        views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
        ),
        name="password_change",
    ),
    django.urls.path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    django.urls.path(
        "password_reset/",
        users.views.CustomPasswordResetView.as_view(),
        name="password_reset",
    ),
    django.urls.path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    django.urls.path(
        "password_reset/confirm/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=django.urls.reverse_lazy(
                "users:password_reset_complete",
            ),
        ),
        name="password_reset_confirm",
    ),
    django.urls.path(
        "password_reset/complete/",
        views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]

# User profile and list
urlpatterns += [
    django.urls.path(
        "user_list/",
        users.views.UserListView.as_view(),
        name="user_list",
    ),
    django.urls.path(
        "user_details/<int:pk>",
        users.views.UserDetailView.as_view(),
        name="user_detail",
    ),
    django.urls.path(
        "profile/",
        users.views.ProfileView.as_view(),
        name="profile",
    ),
]

food_control/users/models.py
import sys

import django.contrib.auth.models as auth_models
import django.db.models
from sorl.thumbnail import get_thumbnail

import users.validators


class UserManager(auth_models.UserManager):
    DOMAINS = {
        "ya.ru": "yandex.ru",
    }
    SYMBOLS = {
        "yandex.ru": "-",
        "gmail.com": "",
    }

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .select_related(
                auth_models.User.profile.related.name,
            )
        )

    def active(self):
        return self.get_queryset().filter(is_active=True)

    def by_mail(self, mail):
        mail = self.normalize_email(mail)
        return self.active().get(email=mail)

    @classmethod
    def normalize_email(cls, email):
        email = super().normalize_email(email).lower()
        try:
            email_name, domain = email.strip().rsplit("@", 1)
            email_name, _ = email_name.split("+", 1)
            domain = cls.DOMAINS.get(domain, domain)

            email_name = email_name.replace(
                ".",
                cls.SYMBOLS.get(domain, "."),
            )
        except ValueError:
            pass
        else:
            email = "@".join(email_name, domain.lower())

        return email


class User(auth_models.User):
    objects = UserManager()

    class Meta:
        proxy = True


class Profile(django.db.models.Model):
    def image_path(self, filename):
        return f"users/{self.user.id}/{filename}"

    user = django.db.models.OneToOneField(
        auth_models.User,
        on_delete=django.db.models.CASCADE,
        related_name="profile",
        null=True,
    )
    birthday = django.db.models.DateTimeField(
        "дата рождения",
        blank=True,
        null=True,
        validators=[users.validators.validate_not_future],
    )
    image = django.db.models.ImageField(
        "аватар",
        blank=True,
        null=True,
        upload_to=image_path,
    )
    attempts_count = django.db.models.PositiveIntegerField(
        "попытки входа",
        default=0,
    )
    block_date = django.db.models.DateTimeField(
        "дата блокировки",
        blank=True,
        null=True,
    )

    def get_image(self):
        return get_thumbnail(self.image, "200x200", crop="center", quality=51)

    class Meta:
        verbose_name = "Профиль пользователя"
        verbose_name_plural = "Профили"


if "makemigrations" not in sys.argv and "migrate" not in sys.argv:
    auth_models.User._meta.get_field("email")._unique = True

food_control/users/forms.py
import django.core.exceptions
import django.forms

from core.forms import BootstrapFormMixin
from users.models import Profile, User


class SignUpForm(
    BootstrapFormMixin,
    django.contrib.auth.forms.UserCreationForm,
):
    class Meta(django.contrib.auth.forms.UserCreationForm.Meta):
        model = User
        fields = (
            User.email.field.name,
            User.username.field.name,
        )

    def clean_username(self):
        username = self.cleaned_data.get("username")

        if "@" in username:
            raise django.core.exceptions.ValidationError(
                "Имя пользователя не может содержать символ '@'",
            )

        return username


class UserChangeForm(
    BootstrapFormMixin,
    django.contrib.auth.forms.UserChangeForm,
):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop("password")

    class Meta(django.contrib.auth.forms.UserChangeForm.Meta):
        model = User
        fields = (
            User.first_name.field.name,
            User.last_name.field.name,
        )


class ProfileForm(
    BootstrapFormMixin,
    django.forms.ModelForm,
):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields[Profile.birthday.field.name].widget = (
            django.forms.DateInput(
                attrs={"type": "date", "class": "form-control"},
            )
        )

    class Meta:
        model = Profile
        fields = (
            Profile.image.field.name,
            Profile.birthday.field.name,
        )
        help_text = {
            Profile.image.field.name: "Введите имя",
            Profile.birthday.field.name: "Введите дату дня рождения",
        }

food_control/users/views.py
from datetime import timedelta
from http import HTTPStatus

import django.conf
import django.contrib.auth
import django.contrib.auth.mixins
import django.contrib.auth.views
import django.core.exceptions
import django.core.mail
import django.http
import django.shortcuts
import django.urls
import django.utils
import django.utils.timezone
import django.views.generic
import multi_form_view


import users.forms
import users.models


class SignUpView(django.views.generic.FormView):
    model = users.models.User
    form_class = users.forms.SignUpForm
    template_name = "users/signup.html"
    success_url = django.urls.reverse_lazy("users:login")

    def form_valid(self, form):
        email = form.cleaned_data.get("email")

        user = form.save(commit=False)
        user.is_active = django.conf.settings.DEFAULT_USER_IS_ACTIVE
        user.save()
        users.models.Profile.objects.create(user=user)

        activation_url = self.request.build_absolute_uri(
            django.urls.reverse("users:activate", args=[user.username]),
        )

        form.save()
        django.core.mail.send_mail(
            "Активация профиля",
            activation_url,
            django.conf.settings.DJANGO_MAIL,
            [email],
            fail_silently=False,
        )
        return super().form_valid(form)


class ActivateView(django.views.generic.View):
    def get(self, request, username):
        user = django.shortcuts.get_object_or_404(
            users.models.User,
            username=username,
        )

        if user.is_active or (
            django.utils.timezone.now() - user.date_joined
        ) > timedelta(
            hours=12,
        ):
            return django.http.HttpResponse(status=HTTPStatus.NOT_FOUND)

        user.is_active = True
        user.save()
        return django.shortcuts.redirect("users:profile")


class ReactivateView(django.views.generic.View):
    def get(self, request, pk):
        user = django.shortcuts.get_object_or_404(users.models.User, pk=pk)

        if user.is_active or (
            django.utils.timezone.now() - user.profile.block_date
        ) > timedelta(
            days=7,
        ):
            return django.http.HttpResponse(status=HTTPStatus.NOT_FOUND)

        user.is_active = True
        user.save()
        return django.shortcuts.redirect("users:profile")


class UserListView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.ListView,
):
    template_name = "users/user_list.html"
    queryset = users.models.User.objects.filter(is_active=True)
    context_object_name = "users"


class UserDetailView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.DetailView,
):
    model = users.models.User
    template_name = "users/user_detail.html"
    context_object_name = "user"


class ProfileView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    multi_form_view.MultiModelFormView,
):
    form_classes = {
        "user_form": users.forms.UserChangeForm,
        "profile_form": users.forms.ProfileForm,
    }
    template_name = "users/profile.html"

    def get_objects(self):
        if self.request.user.profile.birthday:
            self.request.user.profile.birthday += timedelta(days=1)
            self.request.user.profile.birthday = (
                self.request.user.profile.birthday.strftime(
                    "%Y-%m-%d",
                )
            )

        return {
            "user_form": self.request.user,
            "profile_form": self.request.user.profile,
        }

    def get_success_url(self):
        return django.urls.reverse("users:profile")

    def forms_valid(self, forms):
        forms["user_form"].save()
        forms["profile_form"].save()

        return super(ProfileView, self).forms_valid(forms)


class CustomPasswordResetView(django.contrib.auth.views.PasswordResetView):
    template_name = "users/password_reset.html"
    email_template_name = "users/password_reset_email.html"

    def form_valid(self, form):
        email = form.cleaned_data.get("email")

        try:
            user = users.models.User.objects.by_mail(email)
        except users.models.User.DoesNotExist:
            user = None

        if not user:
            form.add_error(
                "email",
                django.core.exceptions.ValidationError(
                    "Пользователь с таким email не найден.",
                ),
            )
            return self.form_invalid(form)

        return super().form_valid(form)

food_control/templates/users/login.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}{% translate "Вход" %}{% endblock  %}

{% block content %}
  <h2 class="mt-4 mb-4">{% translate "Войти в аккаунт" %}</h2>
  <form method="post">
    {% csrf_token %}
    {% include "includes/form.html" %}
    <br>
    <input class="btn btn-primary" type="submit" value="{% translate 'Подтвердить' %}">
  </form>
  <br>
  <a href="{% url 'users:signup' %}" class="m-2">{% translate "Зарегистрироваться" %}</a>
  <a href={% url "users:password_reset" %}>{% translate "Забыли пароль?" %}</a>
{% endblock  %}

food_control/templates/users/logout.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% translate "Выход" %}{% endblock  %}

{% block content %}
  <h2 class="mt-4">{% translate "Вы успешно вышли" %}.</h2>
{% endblock  %}

food_control/templates/users/password_change.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% translate "Изменение пароля" %}{% endblock  %}

{% block content %}
  <h2 class="mt-4 mb-4">{% translate "Изменение пароля" %}</h2>
  <form method="post">
    {% csrf_token %}
    {% include "includes/form.html" %}
    <br>
    <input class="btn btn-primary" type="submit" value="{% translate 'Подтвердить' %}">
  </form>
  <br>
{% endblock  %}

food_control/templates/users/password_change_done.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% translate "Изменение" %}{% endblock  %}

{% block content %}
  <h2 class="mt-4">{% translate "Вы успешно изменили пароль" %}.</h2>
{% endblock  %}

food_control/templates/users/password_reset.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% translate "Восстановление пароля" %}{% endblock  %}

{% block content %}
	<h2 class="mt-4 mb-4">{% translate "Восстановление пароля" %}</h2>
	<form method="post">
		{% csrf_token %}
		{% include "includes/form.html" %}
		<br>
		<input class="btn btn-primary" type="submit" value="{% translate 'Подтвердить' %}">
	</form>
	<br>
{% endblock  %}

food_control/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% translate "Восстановление пароля" %}{% endblock %}

{% block content %}
  <h2 class="mt-4">{% translate "Вы успешно восстановили пароль" %}.</h2>
{% endblock  %}

food_control/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% translate "Восстановление пароля" %}{% endblock  %}

{% block content %}
	<h2 class="mt-4 mb-4">{% translate "Восстановление пароля" %}</h2>
	<form method="post">
		{% csrf_token %}
		{% include "includes/form.html" %}
		<br>
		<input class="btn btn-primary" type="submit" value="{% translate "Подтвердить" %}">
	</form>
{% endblock  %}

food_control/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% translate "Восстановление пароля" %}{% endblock  %}

{% block content %}
  <h2 class="mt-4">{% translate "Письмо отправлено вам на почту" %}.</h2>
{% endblock  %}

food_control/templates/users/password_reset_email.html
{% load i18n %}
{% autoescape off %}
{% blocktrans %}Вы получили это письмо, потому что вы (или кто-то другой) запросили восстановление пароля.{% endblocktrans %}

{% translate "Пожалуйста, перейдите по следующей ссылке, чтобы установить новый пароль:" %}
{{ protocol }}://{{ domain }}/users/password_reset/confirm/{{ uid }}/{{ token }}

{% translate "Если вы не запрашивали сброс пароля, просто проигнорируйте это письмо." %}

{% translate "Спасибо!" %}
{% endautoescape %}

food_control/templates/users/profile.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% translate "Мой профиль" %}{% endblock %}
{% block content %}
  <h1 class="mt-3">
    {% translate "Мой профиль" %}
  </h1>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
      {% with form=forms.user_form %}
        {% include "includes/form.html" %}
      {% endwith %}
      {% with form=forms.profile_form %}
        {% include "includes/form.html" %}
      {% endwith %}
    <br>
    <button type="submit" class="btn btn-primary">{% translate "Сохранить изменения" %}</button>
  </form>
  <form action="{% url 'users:logout' %}" method="post" style="display: inline;">
    {% csrf_token %}
    <button type="submit" class="btn btn-warning mt-3">{% trans "Выйти" %}</button>
  </form>
  <a href="{% url 'users:password_change' %}" class="btn btn-success mt-3">{% translate "Сменить пароль" %}</a>
{% endblock %}

food_control/templates/users/signup.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% translate "Регистрация" %}{% endblock  %}

{% block content %}
  <h2 class="mt-4 mb-4">{% translate "Регистрация" %}</h2>
  <form method="post">
    {% csrf_token %}
    {% include "includes/form.html" %}
    <br>
    <input class="btn btn-primary" type="submit" value="{% translate 'Подтвердить' %}">
  </form>
  <br>
{% endblock  %}

food_control/templates/users/user_detail.html
{% extends "base.html" %}
{% load i18n static %}
{% block title %}{% translate "Информация о пользователе" %}{% endblock %}
{% block content %}
	<div class="container mt-4">
		<div class="text-center">
			{% if user.profile.image %}
				<img src="{{ user.profile.get_image.url }}" alt="Профиль" class="rounded-circle mb-3">
			{% else %}
				<img src="{% static 'img/racoon.jpg' %}" alt="image" class="rounded-circle mb-3 racoon">
			{% endif %}
			{% if user.first_name and user.last_name %}
				<h2 class="mb-3">{{ user.get_full_name }}</h2>
			{% else %}
				<h2 class="mb-3">{% translate "Имя не указано" %}</h2>
			{% endif %}

			<p class="text-muted">{{ user.email }}</p>

			{% if user.profile.birthday %}
				<p>{% translate "Дата рождения: " %}<strong>{{ user.profile.birthday|date:"d.m" }}</strong></p>
			{% else %}
				<p>{% translate "Дата рождения не указана" %}</p>
			{% endif %}
		</div>
	</div>
{% endblock %}

food_control/templates/users/user_list.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}Профиль{% endblock %}
{% block content %}
	<h1>{% translate "Список активных пользователей" %}</h1>
	<ul>
		{% for user in users %}
			<div class="mt-3">
				{% include "includes/user_card.html" %}
			</div>
		{% endfor %}
	</ul>
{% endblock %}